# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import station_pb2 as station__pb2


class StationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get = channel.unary_stream(
        '/noaa.StationService/get',
        request_serializer=station__pb2.Empty.SerializeToString,
        response_deserializer=station__pb2.Station.FromString,
        )
    self.send = channel.unary_unary(
        '/noaa.StationService/send',
        request_serializer=station__pb2.Station.SerializeToString,
        response_deserializer=station__pb2.Empty.FromString,
        )


class StationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get': grpc.unary_stream_rpc_method_handler(
          servicer.get,
          request_deserializer=station__pb2.Empty.FromString,
          response_serializer=station__pb2.Station.SerializeToString,
      ),
      'send': grpc.unary_unary_rpc_method_handler(
          servicer.send,
          request_deserializer=station__pb2.Station.FromString,
          response_serializer=station__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'noaa.StationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
