# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: station.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='station.proto',
  package='noaa',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rstation.proto\x12\x04noaa\"\x94\x01\n\x07Station\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07mindate\x18\x03 \x01(\t\x12\x0f\n\x07maxdate\x18\x04 \x01(\t\x12\x11\n\televation\x18\x05 \x01(\x02\x12\x15\n\relevationUnit\x18\x06 \x01(\t\x12\x11\n\tlongitude\x18\x07 \x01(\x02\x12\x10\n\x08latitude\x18\x08 \x01(\x02\"\x07\n\x05\x45mpty2]\n\x0eStationService\x12%\n\x03get\x12\x0b.noaa.Empty\x1a\r.noaa.Station\"\x00\x30\x01\x12$\n\x04send\x12\r.noaa.Station\x1a\x0b.noaa.Empty\"\x00\x62\x06proto3')
)




_STATION = _descriptor.Descriptor(
  name='Station',
  full_name='noaa.Station',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='noaa.Station.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='noaa.Station.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mindate', full_name='noaa.Station.mindate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxdate', full_name='noaa.Station.maxdate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='noaa.Station.elevation', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elevationUnit', full_name='noaa.Station.elevationUnit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='noaa.Station.longitude', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='noaa.Station.latitude', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=172,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='noaa.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['Station'] = _STATION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Station = _reflection.GeneratedProtocolMessageType('Station', (_message.Message,), dict(
  DESCRIPTOR = _STATION,
  __module__ = 'station_pb2'
  # @@protoc_insertion_point(class_scope:noaa.Station)
  ))
_sym_db.RegisterMessage(Station)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'station_pb2'
  # @@protoc_insertion_point(class_scope:noaa.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_STATIONSERVICE = _descriptor.ServiceDescriptor(
  name='StationService',
  full_name='noaa.StationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=183,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='noaa.StationService.get',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='send',
    full_name='noaa.StationService.send',
    index=1,
    containing_service=None,
    input_type=_STATION,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATIONSERVICE)

DESCRIPTOR.services_by_name['StationService'] = _STATIONSERVICE

# @@protoc_insertion_point(module_scope)
